name: e2e

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  e2e-kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '~1.18'

    - name: Install kind binary
      run: |
        make kind

    - name: Run e2e tests
      run: |
        make e2e KIND=hack/tools/bin/kind
